### ISSUE TITLE
esprima not reporting *what* is actually wrong

### ISSUE THREAD

**Issue by Pomax** [substack/node-falafel#31]
we're apparently using falafel as part of bulkify's static modules, and are running into the problem that the version of esprima bundled does not report what's going wrong when something goes wrong. Looking at the version bundled, you're using 1.1.0-dev from quite a while ago, rather than the current 1.2.2

Could this be updated and a new version of falafel published to npm?

**Comment by goto-bus-stop** [comment]
falafel now uses a modern version of acorn. Thanks!
