### ISSUE TITLE
bump to acorn@~1?

### ISSUE THREAD

**Issue by tunnckoCore** [substack/node-falafel#39]
and release falafel as v2, cuz there should have breaking changes between acorn@0 and acorn@1
one of them [is `loc` option to `locations`](https://github.com/marijnh/acorn#main-parser) so then you should update [coverify#L34](https://github.com/substack/coverify/blob/master/index.js#L34) to `locations`.

**Comment by tunnckoCore** [comment]
@substack ping

**Comment by seangenabe** [comment]
Should be closed re: #55.

**Comment by tunnckoCore** [comment]
Cool. Know need bump to v4 :P

@substack why not @greenkeeper?

**Comment by shinnn** [comment]
Fixed in https://github.com/substack/node-falafel/pull/62

**Comment by goto-bus-stop** [comment]
Now up to v7! Thanks for the report.
