### ISSUE TITLE
Require acorn only if other parse is not set

### ISSUE THREAD

**Issue by royriojas** [substack/node-falafel#50]
It seems that `acorn` is failing when used inside electron/atom.

https://github.com/royriojas/esformatter-jsx/issues/31#issuecomment-147220878

I used this inside `esformatter-jsx` and this module is failing when required inside `atom-esformatter`. 

I was debugging the issue and found that `acorn` couldn't be required. The good part is that I'm actually using `babel-core` as the parser and it didn't have any issue inside `electron/atom` so if `acorn` is not used, maybe it is pointless to require it?

what do you think?

**Comment by goto-bus-stop** [comment]
Looks like this is no longer an issue in newer acorn versions :tada:
