### ISSUE TITLE
Bump Acorn to ~3.0

### ISSUE THREAD

**Issue by salemhilal** [substack/node-falafel#53]
It looks like the Acorn version used by Falafel is getting pretty dated. 

I noticed this because I use [jsfmt](https://github.com/rdio/jsfmt) in an Atom editor plugin I maintain, and the version of acorn used in Falafel has content security issues that have [since been remedied](https://github.com/ternjs/acorn/commit/aed55f3881beb1ea26d8622ada9973839b2b7175). 

Let me know if any additional details are needed.

**Comment by gunderson** [comment]
This also causes all `browserify-transform-tools` based plugins to fail when using es6 syntax

**Comment by shinnn** [comment]
Fixed in https://github.com/substack/node-falafel/pull/62

**Comment by goto-bus-stop** [comment]
Now up to v7! Thanks for the report.
