### ISSUE TITLE
Fix buffer

### ISSUE THREAD

**Issue by bastien-roucaries** [substack/node-falafel#68]
Please apply this patch
``
commit e05cf85952530d4786191f3a55be46dbff8c0758 (HEAD -> patched)
Author: Bastien Roucariès <rouca@debian.org>
Date:   Tue Jan 1 22:38:05 2019 +0100

    Fix Buffer()
    
    Forwarded:

diff --git a/test/opts.js b/test/opts.js
index bcfed62..52a58d9 100644
--- a/test/opts.js
+++ b/test/opts.js
@@ -70,7 +70,7 @@ test('opts.source', function (t) {
 test('Buffer opts.source', function (t) {
     t.plan(5);
     
-    var src = Buffer('(function () {'
+    var src = Buffer.from('(function () {'
         + 'var xs = [ 1, 2, [ 3, 4 ] ];'
         + 'var ys = [ 5, 6 ];'
         + 'g([ xs, ys ]);'
@@ -103,7 +103,7 @@ test('Buffer opts.source', function (t) {
 test('Buffer source', function (t) {
     t.plan(5);
     
-    var src = Buffer('(function () {'
+    var src = Buffer.from('(function () {'
         + 'var xs = [ 1, 2, [ 3, 4 ] ];'
         + 'var ys = [ 5, 6 ];'
         + 'g([ xs, ys ]);'
```

**Comment by Loilo** [comment]
I fixed this in my fork of falafel. If you're interested, take a look at [Yufka](https://www.npmjs.com/package/yufka).

**Comment by goto-bus-stop** [comment]
Thanks! Fixed in :package: 2.2.3.
