### ISSUE TITLE
Missing LICENSE file.

### ISSUE THREAD

**Issue by ericsnowcurrently** [substack/node-falafel#70]
I found 2 license-related problems:

- [x] missing `LICENSE` file at top of repo
   + it should contain your copyright info
   + you've indicated MIT: https://opensource.org/licenses/MIT
- [x] missing `LICENSE` file in the release tarball (under https://registry.npmjs.org/)

**Comment by goto-bus-stop** [comment]
Fixed in :package: 2.2.3. Thanks!
