### ISSUE TITLE
Why does the update fields on the update function need to be copied?

### ISSUE THREAD

**Issue by yangsu** [substack/node-falafel#8]
In the code below, the fields on the existing `update` function are copied over to the `update` function before it's attached to the `node`. Why is this necessary?

https://github.com/substack/node-falafel/blob/master/index.js#L62-L68
```javascript
    if (node.update && typeof node.update === 'object') {
        var prev = node.update;
        Object.keys(prev).forEach(function (key) {
            update[key] = prev[key];
        });
        node.update = update;
    }
```

**Comment by chrahunt** [comment]
@yangsu You can see the modification in 78378951d04177158e3fe7e912004b9ff854fcea to resolve #3 concerning the `update` field properties of For loops being hidden by the addition of the `update` function.

**Comment by yangsu** [comment]
thank you. completely forgot about this.
